const places = ['A park in Utah',
  'City Creek Mall in Utah',
  'A diner in Idaho',
  'The Rocky Mountains (Utah)',
  'An expo center in Arizona',
  'An arcade in Arizona',
  'A library in Arizona',
  'A lodge in Utah',
  'A theater at BYU',
  'A cosplay shop in Japan',
  'An outdoor festival in Texas',
  'A BBQ restaurant in Texas',
  'A tall building in Texas',
  'A zoo in Texas',
  'An amusement park in Texas',
  'A botanical garden in Texas',
  'A music venue in Texas',
  'A science museum in Connecticut',
  'A beach in California',
  'A game show in California',
  'The docks in California',
  'A forest in California',
  'A train station in Utah',
  'An airport in Utah',
  'A grocery store in Arizona',
  'A park in Universe City, a futuristic city',
  'A shopping center in Universe City, a futuristic city',
  'A tech expo in Universe City, a futuristic city',
  'An arcade in Universe City, a futuristic city',
  'A library in Universe City, a futuristic city',
  'A theater in Universe City, a futuristic city',
  'A cosplay shop in Universe City, a futuristic city',
  'A tall building in Universe City, a futuristic city',
  'An amusement park in Universe City, a futuristic city',
  'A botanical garden in Universe City, a futuristic city',
  'An immersive music venue in Universe City, a futuristic city',
  'A science museum in Universe City, a futuristic city',
  'A beach in Universe City, a futuristic city',
  'A hyperloop train station in Universe City, a futuristic city',
  'The docks in Universe city, a futuristic city',
  'A park in an isekai fantasy city',
  'A marketplace in an isekai fantasy city',
  'A clothes shop in an isekai fantasy city',
  'A restaurant in an isekai fantasy city',
  'A plaza in an isekai fantasy city',
  'A library in an isekai fantasy city',
  'A castle in an isekai fantasy city',
  'A nobility palace in an isekai fantasy city',
  'An outdoor festival in an isekai fantasy city',
  'A zoo in an isekai fantasy city',
  'A music venue in an isekai fantasy city',
  'A museum in an isekai fantasy city',
  'A beach in an isekai fantasy port town',
  'The mountains in an isekai fantasy world',
  'A lodge in an isekai fantasy world',
  'A forest in an isekai fantasy world',
  'A fort in an isekai fantasy world',
  'Oslo, Norway',
  'Munich, Germany',
  'London, United Kingdom'];