const places2 = ["Majimoji Rurumo",
  "Howl's Moving Castle",
  "Hanamaru Kindergarten",
  "Ro-Kyu-Bu!",
  "Lucky Star",
  "Denpa Onna to Seishun Otoko",
  "Barakamon",
  "Hibike! Euphonium",
  "Working!!",
  "A-Channel",
  "Rozen Maiden",
  "Squid Girl",
  "Yamada-kun and the Seven Witches",
  "Gakkougurashi!",
  "Is the Order a Rabbit?",
  "Gosick",
  "Himouto! Umaru-Chan",
  "Chuunibyou demo Koi ga Shitai!",
  "Non Non Biyori",
  "Kantai Collection: KanColle",
  "No Game No Life",
  "Miyakawa-Ke no Kuufuku",
  "Listen to Me, Girls. I Am Your Father!",
  "Danchigai",
  "Acchi Kocchi",
  "Hidan no Aria",
  "Kiniro Mosaic",
  "Himegoto",
  "Aiura",
  "Puella Magi Madoka Magica",
  "Mahou Shoujo Nante Mou Ii Desukara.",
  "KONOSUBA",
  "Yuru Yuri",
  "Encouragement of Climb",
  "Yami to Boushi to Hon no Tabibito",
  "Sleeping With Hinako",
  "Shirobako",
  "Dream Eater Merry",
  "AnoHana",
  "Engaged to the Unidentified",
  "If Her Flag Breaks",
  "The Devil is a Part-Timer!",
  "Chi's Sweet Home",
  "Shomin Sample",
  "YUKI YUNA IS A HERO",
  "Joshiraku",
  "Wakaba Girl",
  "D-Frag!",
  "GJ-Bu",
  "Kill Me Baby",
  "Denki-gai no Honya-san",
  "Girls und Panzer",
  "Sora no Method",
  "Punch Line",
  "Croisée in a Foreign Labrynth",
  "NouCome",
  "INVADERS of the ROKUJYOMA!?",
  "Poyopoyo",
  "K-On!",
  "Kokoro Connect",
  "Gekkan Shoujo Nozaki-Kun",
  "Problem Children are Coming from Another World",
  "Amagi Brilliant Park",
  "Wish Upon the Pleiades",
  "Oreshura",
  "Date a Live",
  "Kino's Journey",
  "Teekyuu",
  "Plastic Neesan",
  "Amaama to Inazuma",
  "NEW GAME!",
  "Love Live! School Idol Project",
  "My Teen Romantic Comedy SNAFU",
  "The Tatami Galaxy",
  "Rewrite",
  "Tantei Opera Milky Holmes",
  "The Melancholy of Haruhi Suzumiya",
  "Black Bullet",
  "Watamote",
  "Love Lab",
  "Angel Beats!",
  "Sabagebu!",
  "Tanaka-Kun is Always Listless",
  "Wagamama High Spec",
  "Inferno Cop",
  "This Art Club Has a Problem!",
  "Magical Girl Raising Project",
  "WWW.WORKING!!",
  "Hanayamata",
  "Nichijou",
  "Magic of Stella",
  "Momokuri",
  "Servant x Service",
  "Outbreak Company",
  "Little Witch Academia",
  "The Pet Girl of Sakurasou",
  "High School Fleet",
  "Space Patrol Luluco",
  "Azumanga Daioh",
  "Aria the Animation",
  "Toradora!",
  "Kanamemo",
  "Spirited Away",
  "Kotoura-San",
  "Scorching Ping-Pong Girls",
  "The World God Only Knows",
  "Bakemonogatari",
  "Gabriel DropOut",
  "Hacka Doll the Animation",
  "Gonna be the Twin-Tail!",
  "Black Rock Shooter (OVA)",
  "Miss Kobayashi's Dragon Maid",
  "Cardcaptor Sakura",
  "The Familiar of Zero",
  "Morita-san wa Mukuchi.",
  "Saekano: How to Raise a Boring Girlfriend",
  "Yuyushiki",
  "FLCL",
  "Gakuen Utopia Manabi Straight!",
  "Hand Shakers",
  "Sakura Quest",
  "Anne Happy",
  "The iDOLM@STER Cinderella Girls",
  "Hinako Note",
  "Eromanga Sensei",
  "Usagi Drop",
  "Saint Seiya",
  "Steins;Gate",
  "Welcome to the NHK",
  "She and Her Cat: Everything Flows",
  "Voices of a Distant Star",
  "Haganai",
  "Flip Flappers",
  "Tenshi no 3P!",
  "Inu X Boku SS",
  "In Another World With My Smartphone",
  "Strawberry Marshmallow",
  "Shugo Chara!",
  "Heaven's Lost Property",
  "Dog Days",
  "Mangirl!",
  "Blade Dance of the Elementalers",
  "WorldEnd",
  "Nyanko Days",
  "Hiyokoi",
  "Blend S",
  "Henneko",
  "Hyperdimension Neptunia",
  "Castle Town Dandelion",
  "Time of Eve",
  "Your Name",
  "Gamers!",
  "Neon Genesis Evangelion",
  "Touhou 6: Embodiment of Scarlet Devil",
  "Touhou 7: Perfect Cherry Blossom",
  "Touhou 8: Imperishable Night",
  "Touhou 10: Mountain of Faith",
  "Slow Start",
  "The Disastrous Life of Saiki K",
  "Air",
  "Hidamari Sketch",
  "Serial Experiments Lain",
  "The Ryuo's Work is Never Done!",
  "I Can't Understand What My Husband is Saying",
  "Yuru Camp",
  "Military!",
  "Initial D",
  "Kanon",
  "Ground Defense Force Mao-Chan",
  "Chitose Get You!",
  "Comic Girls",
  "The Melancholy of Haruhi-Chan Suzumiya",
  "Haiyore! Nyaruko-San",
  "Clannad",
  "Takagi-San",
  "A Place Further Than the Universe",
  "Mob Psycho 100",
  "Death Note",
  "Needless",
  "Cells at Work!",
  "Indian Summer",
  "Unlimited Fafnir",
  "Baka and Test - Summon the Beasts -",
  "C - Control",
  "Searching for the Full Moon",
  "Pastel Memories",
  "Daily Lives of High School Boys",
  "Endro!",
  "Kaguya-Sama: Love is War",
  "The Fruit of Grisaia",
  "Asobi Asobase",
  "Hayate the Combat Butler!",
  "The Helpful Fox Senko-San",
  "Wataten!: An Angel Flew Down To Me",
  "Honobono Log",
  "If It's for My Daughter, I'd Even Defeat a Demon Lord",
  "Seitokai no Ichizon",
  "Pop Team Epic",
  "Mitsuboshi Colors",
  "Saki",
  "Hitoribocchi no Marumaru Seikatsu",
  "He is My Master",
  "The Demon Girl Next Door",
  "Re:Zero",
  "Is This a Zombie?",
  "GA: Geijutsuka Art Design Class",
  "Genshiken",
  "Pani Poni Dash!",
  "Re:Zero Shorts",
  "Plastic Memories",
  "A Certain Scientific Railgun",
  "Nekopara",
  "A Certain Magical Index",
  "BOFURI",
  "Toilet-Bound Hanako-kun",
  "After School Dice Club",
  "Okami-San and Her Seven Companions",
  "Isekai Quartet",
  "Princess Principal",
  "My Next Life as a Villainess: All Routes Lead to Doom!",
  "Princess Connect! Re:Dive",
  "Baccano!",
  "I've Been Killing Slimes for 300 Years and Maxed Out My Level",
  "Shadows House",
  "Silver Spoon",
  "By the Grace of the Gods",
  "Knight's & Magic",
  "Majo no Tabitabi",
  "Sleepy Princess in the Demon Castle",
  "Comic Psychosomatic Medicine",
  "Remake Our Life!",
  "Little Busters!",
  "Pita-Ten",
  "Ms. Vampire who lives in my neighborhood.",
  "Null Peta",
  "Dragon Goes House-Hunting",
  "Himesama Goyoujin",
  "Star Wars: Visions",
  "Mushoku Tensei: Jobless Reincarnation",
  "Azur Lane: Slow Ahead!",
  "World Conquest Zvezda Plot",
  "My Senpai is Annoying!",
  "Sgt. Frog",
  "Kuma Kuma Kuma Bear",
  "Planetarian",
  "Kowarekake no Orgel",
  "The Great Jahy Will Not Be Defeated!",
  "Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside",
  "The Vampire Dies in No Time",
  "In the Land of the Leadale",
  "Dragon Ball",
  "LBX Girls",
  "Umi Monogatari",
  "The Duke of Death and His Maid",
  "Spy x Family",
  "Aharen-san wa Hakarenai",
  "Kaginado",
  "RPG Real Estate",
  "Mahjong Soul Pon",
  "Magical Girl Lyrical Nanoha",
  "Kemono Friends",
  "Hakone-Chan",
  "Parallel World Pharmacy",
  "Recorder and Randsell",
  "Miss Shachiku and the Little Baby Ghost",
  "Bocchi the Rock!",
  "Astarotte's Toy",
  "Amanchu!",
  "Onimai: I'm Now Your Sister",
  "Ya Boy Kongming!",
  "Oshi no Ko",
  "The iDOLM@STER Cinderella Girls: U149",
  "My Unique Skill Makes Me OP even at Level 1",
  "Am I Actually the Strongest?",
  "Recovery of an MMO Junkie",
  "Pokemon XY",
  "Tearmoon Empire",
  "Flying Witch",
  "The Boy and the Heron",
  "Fluffy Paradise",
  "Alice or Alice",
  "Di Gi Charat",
  "Reincarnated as a Sword",
  "A Silent Voice",
  "Rail Romanesque",
  "When Supernatural Battles Become Commonplace",
  "Frieren: Beyond Journey's End",
  "Oomuro-ke",
  "The Yakuza's Guide to Babysitting",
  "My Deer Friend Nokotan",
  "Sasami Magical Girls Club",
  "Porco Rosso",
  "Puniru is a Kawaii Slime",
  "New York City",
  "Los Angeles",
  "San Francisco",
  "Chicago",
  "Austin",
  "San Antonio",
  "Portland, Oregon",
  "Portland, Maine",
  "Seattle",
  "Vancouver",
  "Las Vegas",
  "Boise",
  "Salt Lake City",
  "Arches National Park",
  "Phoenix",
  "Grand Canyon",
  "Albuquerque",
  "Santa Fe",
  "Denver",
  "Missoula",
  "Philadelphia",
  "New Jersey",
  "Yellowstone National Park",
  "Oklahoma City",
  "Kansas City",
  "Lincoln, Nebraska",
  "Mount Rushmore",
  "Fargo, North Dakota",
  "New Orleans",
  "Fort Smith, Arkansas",
  "Branson, Missouri",
  "St. Louis",
  "Dubukue, Iowa",
  "Mall of America",
  "Milwaukee",
  "Detroit",
  "Chicago",
  "Indianapolis",
  "Jackson, Mississippi",
  "Mobile, Alabama",
  "Disney World",
  "Miami",
  "Atlanta",
  "Nashville",
  "Louisville",
  "Cleveland",
  "Charleston, South Carolina",
  "Charleston, West Virginia",
  "Raleigh",
  "Charlotte, North Carolina",
  "Washington, D.C.",
  "Virginia Beach",
  "Baltimore",
  "Dover",
  "Buffalo",
  "New Haven",
  "Providence, Rhode Island",
  "Boston",
  "Portsmouth, New Hampshire",
  "Burlington, Vermont",
  "Anchorage",
  "Honolulu",
  "Edmonton",
  "Saskastoon",
  "Winnipeg",
  "Toronto",
  "Ottawa",
  "Montreal",
  "Halifax",
  "London, United Kingdom",
  "Paris, France",
  "Strasbourg",
  "Madrid",
  "Barcelona",
  "Lisbon",
  "Glasgow",
  "Cardiff",
  "Belfast",
  "Dublin",
  "Brussels",
  "Amsterdam",
  "Oslo",
  "Bergen",
  "Stockholm",
  "Copenhagen",
  "Munich",
  "Berlin",
  "Vienna",
  "Helsinki",
  "Riga",
  "Warsaw",
  "Prague",
  "Bratislava",
  "Budapest",
  "Bern",
  "Milan",
  "Venice",
  "Rome",
  "Athens",
  "Iceland",
  "Tokyo",
  "Osaka",
  "Sapporo",
  "Okinawa",
  "Seoul",
  "Sydney",
  "Auckland"
];